name: qrview
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0+2
  # video_player: ^2.9.2
  permission_handler: ^11.3.1
  # mobile_scanner: ^6.0.2
  # pretty_qr_code: ^3.3.0
  ai_barcode_scanner: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
